name: Build

on:
  push:
    branches:
      - main

    tags:
      - "*"
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          bun-version: ">=1"
          bun-repo: "oven-sh/bun"
          cache: true
          # cache-bin: true
      - name: Install Dependencies
        run: |
          cp .env.example .env
          # source .env.example
          # bun i
          bun i

      - name: Write environment
        run: |
          echo "${{ secrets.ENV }}" | tr ' ' '\n' >> .env

      - name: Build
        run: |
          bun run build
